apiVersion: v1
kind: Service
metadata:
  name: pdf-rag-service
spec:
  type: NodePort
  selector:
    app: pdf-rag
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      nodePort: 30001
